### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by NogerbekNurzhan** [pinax/pinax-referrals#43] opened 2018-05-21 18:47 UTC
Hello! :)

I am trying to create referral system in my Django project. I found your very interesting app and want to test it for this task.

From documentation its not clear how correctly to use it and there is no example. As I understand we need make next steps:

1) Create `Profile `models with such code:
```
from django.contrib.auth.models import User
from django.dispatch import receiver
from account.signals import user_signed_up  # django-user-account app
from pinax.referrals.models import Referral

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    referral = models.OneToOneField(Referral, null=True, on_delete=models.CASCADE)

@receiver(user_signed_up)
def handle_user_signed_up(sender, user, form, **kwargs):
    Referral.create(redirect_to=user.profile.get_absolute_url())
```
2) Сreate custom signup view:
```
from account.views import SignupView
from pinax.referrals.models import Referral


class RegistrationView(SignupView):

    def after_signup(self, form):
        super(RegistrationView, self).after_signup(form)
        Referral.record_response(self.request, "USER_SIGNUP")
```
How correct are my steps? Could you give a simple example for the understanding please?

**Comment by KatherineMichel** [comment] 2018-08-02 19:02
Closing this issue as an apparent duplicate of https://github.com/pinax/pinax-referrals/issues/44

**Closed by KatherineMichel** 2018-08-02 19:02 UTC
